// <auto-generated />
using System;
using Agenda.APi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agenda.APi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200412195440_AddedUserEmployee")]
    partial class AddedUserEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Agenda.APi.Models.Employee", b =>
                {
                    b.Property<int>("IdEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactNumEmp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailEmp")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEmp")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHashEmp")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSaltEmp")
                        .HasColumnType("BLOB");

                    b.Property<string>("UsernameEmp")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmp");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Agenda.APi.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("values");
                });
#pragma warning restore 612, 618
        }
    }
}
